### ISSUE TITLE
How can I install this?

### ISSUE THREAD

**Issue by feluxe** [dbrattli/aioreactive#20]
Hi there!

This lib looks neat! I'm really excited to give it a try!

Is there any info on how to install this?

I think it would be cool if there was an *Install* or *Getting Started* section in  README.md. :)

**Comment by favetelinguis** [comment]
Check this out https://pypi.org/project/aioreactive/

Else since it has a setup.py file just clone the repo and run pip install .

**Comment by rmcgregor1990** [comment]
A pypi badge at the root of the readme to link to this would also be great addition:
[![PyPI version](https://badge.fury.io/py/aioreactive.svg)](https://badge.fury.io/py/aioreactive)

**Comment by dbrattli** [comment]
Fixed with v0.6.0
