### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by JerzySpendel** [dbrattli/aioreactive#23]
I would rather use this library than RxPY, so if you're not planning to develop it anymore I would be interested in continuing it :)

**Comment by JerzySpendel** [comment]
Ok, I guess so :P

**Comment by JerzySpendel** [comment]
xD

**Comment by wysockipiotr** [comment]
xD

**Comment by stucash** [comment]
what a promising alternative to rxpy, that has been saddly abandoned.

**Comment by dbrattli** [comment]
Yes, ... and no. A new implementation is now on it's way. Thanks for the interest. https://github.com/dbrattli/aioreactive/pull/24/files

**Comment by JerzySpendel** [comment]
@dbrattli Cool!

**Comment by dbrattli** [comment]
FYI: It will be based on the new [Expression](https://github.com/dbrattli/expression) library so currently aioreactive is waiting for the `Map` implementation to get ready there.
