### ISSUE TITLE
Implementing reduce

### ISSUE THREAD

**Issue by francipvb** [dbrattli/aioreactive#29]
Hello,

Is there a reduce operator or not yet?

If not, let me know and I will try to implement it.

**Comment by dbrattli** [comment]
Yes, please. Operators like scan, fold and aggregate would be highly appreciated.

**Comment by francipvb** [comment]
I will send you a PR with implementations for scan and reduce, sync and async variants.

**Comment by rafalkrupinski** [comment]
both aioreacrive.reduce and AsyncRx.reduce are implemented. I guess the issue can be closed?
