### ISSUE TITLE
Stream Fork

### ISSUE THREAD

**Issue by Arttii** [dbrattli/aioreactive#3]
I was wondering if there is a nice way to "fork" a stream, meaning to use the filter operator to get a number of streams from one stream, based on a certain condition for example.

Also please let me know if issues are the wrong place to ask these questions.

**Comment by dbrattli** [comment]
To split a stream in to multiple streams:

```python
from aioreactive.producer import Producer
import aioreactive.producer.operators as ops

xs = Producer.from_iterable(range(10))
odds = xs | ops.filter(lambda x % 2 == 1)
evens = xs | ops.filter(lambda x: x % 2 == 0)
...
```
Perfectly ok to ask questions in issues.

**Comment by Arttii** [comment]
That's what I tried, but if I start both streams and add two simple print sink to each,  only one gets printed. Also tried with an async iterator.
There is nothing special to do to start these is there?



On Sun, Dec 4, 2016 at 7:31 PM +0100, "Dag Brattli" <notifications@github.com<mailto:notifications@github.com>> wrote:


To split a stream in to multiple streams:

from aioreactive.producer import Producer
import aioreactive.producer.operators as ops

xs = Producer.from_iterable(range(10))
odds = xs | ops.filter(lambda x % 2 == 1)
evens = xs | ops.filter(lambda x: x % 2 == 0)
...

Perfectly ok to ask questions in issues.

-

**Comment by dbrattli** [comment]
Have a look at this [example]( https://github.com/dbrattli/aioreactive/blob/master/examples/streams/split.py).

**Comment by Arttii** [comment]
Ha cool, that's exactly what I ended up doing.

**Comment by dbrattli** [comment]
Yes, that is expected behavior. This is what's called "cold" observables in the Rx world. You can turn them "hot" by publishing. Not a 'publish()' operator in aioreactive yet, but you can simulate it by using an `AsyncStream` as your sink. Thus you split from the `AsyncStream`, then you start the `from_iterable()` using your stream instead of the sink (a stream is also a sink). 

Something like:

```python
xs = Producer.from_iterable()

ys = AsyncStream()
odds = ys | ops.filter(lambda x: x % 2 == 1)
evens = ys | ops.filter(lambda x: x % 2 == 0)

await start(odds, FuncSink(mysink))
await start(evens, FuncSink(mysink))
await start(xs, ys)
```

**Comment by Arttii** [comment]
Ha, cool. I guess an operator like that would have to mimic what the AsyncStreamFactory does for the start? Create the intermediate stream and connect them up together?
