### ISSUE TITLE
Python 3.11 support?

### ISSUE THREAD

**Issue by austinnichols101** [dbrattli/aioreactive#39]
pip install using python 3.11 returns the following error:
```
ERROR: Ignored the following versions that require a different python version: 0.16.0 Requires-Python >=3.9,<3.11
ERROR: Could not find a version that satisfies the requirement aioreactive==0.17.0 (from versions: 0.2.0, 0.2.1, 0.3.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0)
ERROR: No matching distribution found for aioreactive==0.17.0

```

**Comment by kfields** [comment]
A new version that supports 3.11 would be nice otherwise I will have to find another solution which I really don't want to do.

**Comment by austinnichols101** [comment]
Same - and python 3.12 is scheduled for 2023-10-02 release.

**Comment by rafalkrupinski** [comment]
🤦 Why would anyone declare `<3.11`?

**Comment by dbrattli** [comment]
Fix the problem, not the blame! Please open a PR.

**Comment by rafalkrupinski** [comment]
It would be much easier for existing users of aioreactive if it kept match function to allow some transition time. This requires either releasing Expression 3.x with `python < 3.11` lifted or bringing back `match` as deprecated.in 4.x

**Comment by rafalkrupinski** [comment]
I've forked Expression 3.3, lifted the python version and used it in my [aioreactive fork](https://github.com/rafalkrupinski/aioreactive/tree/py4).
Works for me in python 3.12.

Can't make PR against a tag in github...

**Comment by austinnichols101** [comment]
@rafalkrupinski - thank you for your efforts!

**Comment by dbrattli** [comment]
I've just fixed Expression library and will make a new release shortly. Then I hope to have some time to update this library as well. Sorry for the slow responses, but have been on vacation for 3 weeks, and now just had surgery on my eyes.

**Comment by rafalkrupinski** [comment]
All the best with your eyes.

I thought Expression was fine, (except perhaps for python <3.10 users) and only this project needed an upgrade from match operator to match expression.

I've only changed Expression so that the upgrade isn't immediately necessary.

**Comment by rafalkrupinski** [comment]
> Please open a PR.

Bro, I don't think I'm qualified :D

**Comment by kstech-roadie** [comment]
Excited to see this fantastic and unique library maintained and extended.  I really enjoy using it in my projects.
